### ISSUE TITLE
Binary Won't Download File

### ISSUE THREAD

**Issue by TheAndroidMaster** [TheAndroidMaster/AAH#7]
Idk why this happens. It works fine compiling from source. Something probably goofed. Here's a bunch of spaghetti it output that I don't understand.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3c pc=0x7f1551239633]

runtime stack:
runtime.throw(0x770f3a, 0x2a)
	/usr/lib/go/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 23 [syscall]:
runtime.cgocall(0x6322b0, 0xc42002fdf8, 0x29)
	/usr/lib/go/src/runtime/cgocall.go:128 +0x64 fp=0xc42002fdb8 sp=0xc42002fd80 pc=0x403274
net._C2func_getaddrinfo(0xc420094480, 0x0, 0xc42008b6e0, 0xc420096088, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:86 +0x55 fp=0xc42002fdf8 sp=0xc42002fdb8 pc=0x53cbb5
net.cgoLookupIPCNAME.func1(0xc420094480, 0x0, 0xc42008b6e0, 0xc420096088, 0x1a, 0x1a, 0xc42009a040)
	/usr/lib/go/src/net/cgo_unix.go:149 +0x13b fp=0xc42002fe40 sp=0xc42002fdf8 pc=0x54213b
net.cgoLookupIPCNAME(0xc420094300, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/cgo_unix.go:149 +0x174 fp=0xc42002ff38 sp=0xc42002fe40 pc=0x53dce4
net.cgoIPLookup(0xc42007a5a0, 0xc420094300, 0x19)
	/usr/lib/go/src/net/cgo_unix.go:201 +0x4d fp=0xc42002ffc8 sp=0xc42002ff38 pc=0x53e3ad
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42002ffd0 sp=0xc42002ffc8 pc=0x4562f1
created by net.cgoLookupIP
	/usr/lib/go/src/net/cgo_unix.go:211 +0xaf

goroutine 1 [select]:
net/http.(*Transport).getConn(0x8d5a20, 0xc42008b200, 0x0, 0x774e03, 0x5, 0xc420094300, 0x1d, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:962 +0x558
net/http.(*Transport).RoundTrip(0x8d5a20, 0xc420132000, 0x8d5a20, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:409 +0x632
net/http.send(0xc420132000, 0x7994a0, 0x8d5a20, 0x0, 0x0, 0x0, 0xc420096060, 0xf8, 0xc420055b98, 0x1)
	/usr/lib/go/src/net/http/client.go:252 +0x185
net/http.(*Client).send(0x9074a0, 0xc420132000, 0x0, 0x0, 0x0, 0xc420096060, 0x0, 0x1, 0x412108)
	/usr/lib/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).Do(0x9074a0, 0xc420132000, 0x774e03, 0x49, 0x0)
	/usr/lib/go/src/net/http/client.go:615 +0x28d
net/http.(*Client).Get(0x9074a0, 0x774e03, 0x49, 0xc420055dd8, 0x18, 0xc420055dd0)
	/usr/lib/go/src/net/http/client.go:396 +0x9d
net/http.Get(0x774e03, 0x49, 0xc420096040, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:370 +0x41
main.DownloadFile(0xc42008e1b0, 0x23, 0x774e03, 0x49, 0x0, 0x0)
	/home/james/go/src/github.com/TheAndroidMaster/AAH/main.go:108 +0xc3
main.main()
	/home/james/go/src/github.com/TheAndroidMaster/AAH/main.go:19 +0x145

goroutine 20 [select]:
net.(*Resolver).LookupIPAddr(0x906820, 0x79be00, 0xc42007a420, 0xc420094300, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/lookup.go:212 +0x50d
net.(*Resolver).internetAddrList(0x906820, 0x79be00, 0xc42007a420, 0x765083, 0x3, 0xc420094300, 0x1d, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/net/ipsock.go:293 +0x5c4
net.(*Resolver).resolveAddrList(0x906820, 0x79be00, 0xc42007a420, 0x765220, 0x4, 0x765083, 0x3, 0xc420094300, 0x1d, 0x0, ...)
	/usr/lib/go/src/net/dial.go:193 +0x50c
net.(*Dialer).DialContext(0xc42007a0c0, 0x79bdc0, 0xc420092030, 0x765083, 0x3, 0xc420094300, 0x1d, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/net/dial.go:375 +0x22b
net.(*Dialer).DialContext-fm(0x79bdc0, 0xc420092030, 0x765083, 0x3, 0xc420094300, 0x1d, 0x4050e6, 0x59eff9, 0xc420092030, 0x717a40)
	/usr/lib/go/src/net/http/transport.go:46 +0x73
net/http.(*Transport).dial(0x8d5a20, 0x79bdc0, 0xc420092030, 0x765083, 0x3, 0xc420094300, 0x1d, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/net/http/transport.go:898 +0x20d
net/http.(*Transport).dialConn(0x8d5a20, 0x79bdc0, 0xc420092030, 0x0, 0x774e03, 0x5, 0xc420094300, 0x1d, 0x0, 0x0, ...)
	/usr/lib/go/src/net/http/transport.go:1143 +0x317
net/http.(*Transport).getConn.func4(0x8d5a20, 0x79bdc0, 0xc420092030, 0xc42008b230, 0xc42007c120)
	/usr/lib/go/src/net/http/transport.go:957 +0x78
created by net/http.(*Transport).getConn
	/usr/lib/go/src/net/http/transport.go:956 +0x363

goroutine 22 [select]:
net.cgoLookupIP(0x79bd80, 0xc42009a340, 0xc420094300, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/cgo_unix.go:212 +0x19f
net.(*Resolver).lookupIP(0x906820, 0x79bd80, 0xc42009a340, 0xc420094300, 0x19, 0x0, 0xc42006cd80, 0xc42009a040, 0x0, 0x0)
	/usr/lib/go/src/net/lookup_unix.go:95 +0x12d
net.(*Resolver).(net.lookupIP)-fm(0x79bd80, 0xc42009a340, 0xc420094300, 0x19, 0x429829, 0x8, 0xc42009a040, 0x0, 0xc42002fea0)
	/usr/lib/go/src/net/lookup.go:192 +0x56
net.glob..func10(0x79bd80, 0xc42009a340, 0xc420086b50, 0xc420094300, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/lookup.go:206 +0xd8
internal/singleflight.(*Group).doCall(0x906810, 0xc4200985a0, 0xc420094300, 0x19, 0xc42008b350)
	/usr/lib/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
	/usr/lib/go/src/internal/singleflight/singleflight.go:88 +0x2d0
```

**Comment by TheAndroidMaster** [comment]
Resolved with #9
